# ACTIONS REQUIRED: Replace YOUR_NAMESPACE_HERE with your namespace.
#
# This file defines the CustomResourceDefinition (CRD) for representing an instance of your
# application. By default, we've defined our instances to be named `seafile`, so that
# they will appear in kubectl via `kubectl get seafiles`. The defined names of the application
# instance type can be changed below.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: seafiles.app.stei.gr
  namespace: YOUR_NAMESPACE_HERE
spec:
  group: app.stei.gr
  scope: Namespaced
  version: v1alpha1
  names: 
    singular: seafile
    plural: seafiles
    kind: Seafile
    listKind: SeafileList
