# ACTIONS REQUIRED: Replace YOUR_NAMESPACE_HERE with your namespace.
#
# This file contains configuration for lostromos for the example application. It defines how
# lostromos will deploy each instance of your application. By default, the templates found in the
# /chart directory in the built image will be used.
#
# If the CustomResourceDefinition (CRD) for this application is modified, please make sure to
# adjust the reference in the `crd` block below.
crd:
  group: app.stei.gr
  name: seafiles
  version: v1alpha1
  namespace: YOUR_NAMESPACE_HERE
helm:
  chart: chart
  namespace: YOUR_NAMESPACE_HERE
  tiller: tiller-deploy.kube-system:44134
  releasePrefix: YOUR_PREFIX_HERE